In [3]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import NearestNeighbors
from scipy import stats as st
import matplotlib.pyplot as plt
from PIL import Image
import scipy

In [4]:
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist
from tensorflow.keras.utils import to_categorical
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

print("Total data points, x pixels, y pixels, color channels")
print(x_train.shape)
print(x_test.shape)

x_train = np.reshape(x_train,(x_train.shape[0],-1))
x_test = np.reshape(x_test,(x_test.shape[0],-1))

print(x_train.shape)
print(x_test.shape)

Total data points, x pixels, y pixels, color channels
(60000, 28, 28)
(10000, 28, 28)
(60000, 784)
(10000, 784)


In [15]:
# kNN
k=10
model = NearestNeighbors(n_neighbors=k)
model.fit(x_train,y_train)
test_neighbors = model.kneighbors_graph(x_test)
print("Picking " + str(k) + " nearest neighbors, a total of " + str(x_train.shape[0]) + " training points with " + str(x_train.shape[1]) + " dimensions")

Picking 10 nearest neighbors, a total of 50000 training points with 3072 dimensions


In [19]:
# test_nearest_neighbors looks through test_neighbors and gets the classifications of the k nearest ones
test_nearest_neighbors = np.empty((y_test.shape[0],k))
# y_pred gets the mode of the nearest neighbors
y_pred = np.empty((y_test.shape[0],1))

print("Total number of test points: " + str(x_test.shape[0]))
for i in range(x_test.shape[0]):
    if i%50 == 0:
        print("i=" + str(i))
    test_nearest_neighbors[i] = y_train[np.nonzero(test_neighbors.toarray()[i])].reshape((k))
    y_pred[i] = int(st.mode(test_nearest_neighbors[i], keepdims=True).mode)

print("Done!")

Total number of test points: 10000
i=0
i=50
i=100
i=150
i=200
i=250
i=300
i=350
i=400
i=450
i=500
i=550
i=600
i=650
i=700
i=750
i=800
i=850
i=900
i=950
i=1000
i=1050
i=1100
i=1150
i=1200
i=1250
i=1300
i=1350
i=1400
i=1450
i=1500
i=1550
i=1600
i=1650
i=1700
i=1750
i=1800
i=1850
i=1900
i=1950
i=2000
i=2050
i=2100
i=2150
i=2200
i=2250
i=2300
i=2350
i=2400
i=2450
i=2500
i=2550
i=2600
i=2650
i=2700
i=2750
i=2800
i=2850
i=2900
i=2950
i=3000
i=3050
i=3100
i=3150
i=3200
i=3250
i=3300
i=3350
i=3400
i=3450
i=3500
i=3550
i=3600
i=3650
i=3700
i=3750
i=3800
i=3850
i=3900
i=3950
i=4000
i=4050
i=4100
i=4150
i=4200
i=4250
i=4300
i=4350
i=4400
i=4450
i=4500
i=4550
i=4600
i=4650
i=4700
i=4750
i=4800
i=4850
i=4900
i=4950
i=5000
i=5050
i=5100
i=5150
i=5200
i=5250
i=5300
i=5350
i=5400
i=5450
i=5500
i=5550
i=5600
i=5650
i=5700
i=5750
i=5800
i=5850
i=5900
i=5950
i=6000
i=6050
i=6100
i=6150
i=6200
i=6250
i=6300
i=6350
i=6400
i=6450
i=6500
i=6550
i=6600
i=6650
i=6700
i=6750
i=6800
i=6850
i=6900
i=6950
i=7000
i

In [23]:
conf_matrix = confusion_matrix(y_test, y_pred)
print(conf_matrix)
print("Accuracy: " + str(np.round(100*conf_matrix.trace()/conf_matrix.sum(),2)) + "%")

[[510   3 109  16  57   4  26   6 269   0]
 [109 183 135  35 183  25  69   6 237  18]
 [100   1 438  38 267  33  54   7  60   2]
 [ 55   3 230 189 231 101 126  10  51   4]
 [ 58   0 265  20 539  13  42  13  50   0]
 [ 45   2 200 140 227 224  87  13  57   5]
 [ 15   0 271  54 343  31 257   0  28   1]
 [ 76   4 183  50 305  55  50 197  73   7]
 [109   6  46  36  67  15  12   6 699   4]
 [127  36 102  48 130  20  55  17 315 150]]
Accuracy: 33.86%
